### ISSUE TITLE
 In android studio on ubuntu does not work

### ISSUE THREAD

**Issue by jlopezdemerlo** [Microsoft/Git-Credential-Manager-for-Mac-and-Linux#92] opened 2018-09-29 10:10 UTC
Hi. Working with Android Studio on ubuntu and since they have upgraded to Azure DevOps does not work. Does not allow push. Request the password repeatedly. I import the project to Azure DevOps and create the repository correctly but not push the repository .... it asks for the password again and again

**Comment by novak** [comment] 2018-09-29 15:33
Is your repository on the new devops domain?

**Comment by novak** [comment] 2018-10-01 02:51
Thanks for the confirmation, this is a duplicate of #90 which will be addressed soon.

**Closed by novak** 2018-10-01 02:51 UTC
Labels: duplicate
